window:
  decorations: buttonless

  padding:
    x: 8
    y: 8

font:
  normal:
    family: Ubuntu Mono

  size: 14

draw_bold_text_with_bright_colors: true

import:
  - ~/.dotfiles/alacritty/everforest.yaml
