
unbind r
bind r source-file ~/.tmux.conf


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-yank'

# vim mode
setw -g mode-keys vi

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g focus-events on
set -g mouse on

set -g status-position top
set -g status-left ""

set -g @catppuccin_status_background "none"
set -g @catppuccin_window_text " #W [#{pane_current_command}]"
set -g @catppuccin_window_current_text " #W [#{pane_current_command}]"


# use Alt-vim keys to navigate
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# split
bind-key v split-window -h
bind-key g split-window -v

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
